# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Programowanie/SEM_6_SR/Laby/lab5/zad2_tor_wiz_na_zywo/zad1_tor_wiz.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0.xci
# IP: The module: 'hdmi_vga_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programowanie/SEM_6_SR/Laby/lab5/zad2_tor_wiz_na_zywo/zad1_tor_wiz.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Programowanie/SEM_6_SR/Laby/lab5/zad2_tor_wiz_na_zywo/zad1_tor_wiz.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Programowanie/SEM_6_SR/Laby/lab5/zad2_tor_wiz_na_zywo/zad1_tor_wiz.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Programowanie/SEM_6_SR/Laby/lab5/zad2_tor_wiz_na_zywo/zad1_tor_wiz.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0.xci
# IP: The module: 'hdmi_vga_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programowanie/SEM_6_SR/Laby/lab5/zad2_tor_wiz_na_zywo/zad1_tor_wiz.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Programowanie/SEM_6_SR/Laby/lab5/zad2_tor_wiz_na_zywo/zad1_tor_wiz.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Programowanie/SEM_6_SR/Laby/lab5/zad2_tor_wiz_na_zywo/zad1_tor_wiz.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
