# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/AGH/semestr_6/Systemy_rekonfigurowalne/laby/2/projects/vision_thor_median/vision_thor.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_1_0/hdmi_vga_vp_1_0.xci
# IP: The module: 'hdmi_vga_vp_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/AGH/semestr_6/Systemy_rekonfigurowalne/laby/2/projects/vision_thor_median/vision_thor.srcs/sources_1/ip/delayLineBRAM/delayLineBRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# IP: D:/AGH/semestr_6/Systemy_rekonfigurowalne/laby/2/projects/vision_thor_median/vision_thor.srcs/sources_1/ip/divider_32_20_0/divider_32_20_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# IP: D:/AGH/semestr_6/Systemy_rekonfigurowalne/laby/2/projects/vision_thor_median/vision_thor.srcs/sources_1/ip/binaryzation_2/binaryzation_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==binaryzation_2 || ORIG_REF_NAME==binaryzation_2} -quiet] -quiet

# IP: D:/AGH/semestr_6/Systemy_rekonfigurowalne/laby/2/projects/vision_thor_median/vision_thor.srcs/sources_1/ip/c_addsub_mxx/c_addsub_mxx.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_addsub_mxx || ORIG_REF_NAME==c_addsub_mxx} -quiet] -quiet

# IP: D:/AGH/semestr_6/Systemy_rekonfigurowalne/laby/2/projects/vision_thor_median/vision_thor.srcs/sources_1/ip/rgb2ycbcr_0_1/rgb2ycbcr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0} -quiet] -quiet

# XDC: d:/AGH/semestr_6/Systemy_rekonfigurowalne/laby/2/projects/vision_thor_median/vision_thor.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_1_0/hdmi_vga_vp_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_vp_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/AGH/semestr_6/Systemy_rekonfigurowalne/laby/2/projects/vision_thor_median/vision_thor.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_1_0/hdmi_vga_vp_1_0.xci
# IP: The module: 'hdmi_vga_vp_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/AGH/semestr_6/Systemy_rekonfigurowalne/laby/2/projects/vision_thor_median/vision_thor.srcs/sources_1/ip/delayLineBRAM/delayLineBRAM.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# IP: D:/AGH/semestr_6/Systemy_rekonfigurowalne/laby/2/projects/vision_thor_median/vision_thor.srcs/sources_1/ip/divider_32_20_0/divider_32_20_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# IP: D:/AGH/semestr_6/Systemy_rekonfigurowalne/laby/2/projects/vision_thor_median/vision_thor.srcs/sources_1/ip/binaryzation_2/binaryzation_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==binaryzation_2 || ORIG_REF_NAME==binaryzation_2} -quiet] -quiet

# IP: D:/AGH/semestr_6/Systemy_rekonfigurowalne/laby/2/projects/vision_thor_median/vision_thor.srcs/sources_1/ip/c_addsub_mxx/c_addsub_mxx.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_addsub_mxx || ORIG_REF_NAME==c_addsub_mxx} -quiet] -quiet

# IP: D:/AGH/semestr_6/Systemy_rekonfigurowalne/laby/2/projects/vision_thor_median/vision_thor.srcs/sources_1/ip/rgb2ycbcr_0_1/rgb2ycbcr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0} -quiet] -quiet

# XDC: d:/AGH/semestr_6/Systemy_rekonfigurowalne/laby/2/projects/vision_thor_median/vision_thor.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_1_0/hdmi_vga_vp_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_vp_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
