# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Programowanie/SEM_6_SR/Laby/lab5/zad2_tor_wiz_na_zywo_copy/zad1_tor_wiz.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
# IP: The module: 'dist_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programowanie/SEM_6_SR/Laby/lab5/zad2_tor_wiz_na_zywo_copy/zad1_tor_wiz.gen/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Programowanie/SEM_6_SR/Laby/lab5/zad2_tor_wiz_na_zywo_copy/zad1_tor_wiz.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
# IP: The module: 'dist_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programowanie/SEM_6_SR/Laby/lab5/zad2_tor_wiz_na_zywo_copy/zad1_tor_wiz.gen/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
