# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: j:/PROGRAMY/Vivado_projekty/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/vp_0/vp_0.xci
# IP: The module: 'vp_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: j:/PROGRAMY/Vivado_projekty/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/vp_0/vp.srcs/sources_1/ip/LUT/LUT.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LUT || ORIG_REF_NAME==LUT} -quiet] -quiet

# XDC: j:/PROGRAMY/Vivado_projekty/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/vp_0/vp.srcs/sources_1/ip/LUT/LUT_ooc.xdc

# IP: j:/PROGRAMY/Vivado_projekty/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/vp_0/vp_0.xci
# IP: The module: 'vp_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: j:/PROGRAMY/Vivado_projekty/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/vp_0/vp.srcs/sources_1/ip/LUT/LUT.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LUT || ORIG_REF_NAME==LUT} -quiet] -quiet

# XDC: j:/PROGRAMY/Vivado_projekty/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/vp_0/vp.srcs/sources_1/ip/LUT/LUT_ooc.xdc
