# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/hdmi_vga_zybo_src/Zybo_HDMI.xdc

# IP: ip/c_addsub_mxx/c_addsub_mxx.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_addsub_mxx || ORIG_REF_NAME==c_addsub_mxx} -quiet] -quiet

# IP: ip/rgb2ycbcr_0_1/rgb2ycbcr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0} -quiet] -quiet

# Block Designs: bd/hdmi_vga/hdmi_vga.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_vga || ORIG_REF_NAME==hdmi_vga} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_dvi2rgb_0_0/hdmi_vga_dvi2rgb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_vga_dvi2rgb_0_0 || ORIG_REF_NAME==hdmi_vga_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_rgb2vga_0_0/hdmi_vga_rgb2vga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_vga_rgb2vga_0_0 || ORIG_REF_NAME==hdmi_vga_rgb2vga_0_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_vga_clk_wiz_0_0 || ORIG_REF_NAME==hdmi_vga_clk_wiz_0_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_xlconstant_0_0/hdmi_vga_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_vga_xlconstant_0_0 || ORIG_REF_NAME==hdmi_vga_xlconstant_0_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_xlconstant_0_1/hdmi_vga_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_vga_xlconstant_0_1 || ORIG_REF_NAME==hdmi_vga_xlconstant_0_1} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_vp_1_0/hdmi_vga_vp_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_vga_vp_1_0 || ORIG_REF_NAME==hdmi_vga_vp_1_0} -quiet] -quiet

# IP: ip/delayLineBRAM/delayLineBRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# IP: ip/divider_32_20_0/divider_32_20_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# IP: ip/binaryzation_2/binaryzation_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==binaryzation_2 || ORIG_REF_NAME==binaryzation_2} -quiet] -quiet

# IP: ip/c_addsub_mxx/c_addsub_mxx.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_addsub_mxx || ORIG_REF_NAME==c_addsub_mxx} -quiet] -quiet

# IP: ip/rgb2ycbcr_0_1/rgb2ycbcr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0} -quiet] -quiet

# XDC: d:/AGH/semestr_6/Systemy_rekonfigurowalne/laby/2/projects/vision_thor_median/vision_thor.gen/sources_1/bd/hdmi_vga/hdmi_vga_ooc.xdc
